#!/usr/bin/env sh

# Sync calendars using org-caldav

SYNC_SCRIPT=$(cat <<EOF
(progn
  (advice-add 'org-icalendar-create-uid :after (lambda (&rest _args) (save-some-buffers t)))
  (with-timeout (60 (warn "calendar sync timed out (60 seconds)") (kill-emacs 1))
    (org-caldav-sync))
  (switch-to-buffer "*org caldav sync result*")
  (princ (buffer-string))
  (princ "\n\n\n---- DEBUG LOG ----\n\n")
  (switch-to-buffer org-caldav-debug-buffer)
  (princ (buffer-string))
  (terpri)
  (save-some-buffers t)
  (kill-emacs 0))
EOF
           )

timestamp=$(date +%FT%H%M%S%z)

tmp=$(mktemp sync-calendar-log-$timestamp-XXXXXX --tmpdir)

echo "Begin sync ($timestamp)"

emacs --batch -u $(whoami) --eval "$SYNC_SCRIPT" 2>$tmp

if [ ! $? ]; then
    echo "There were errors when performing the sync, please see '$tmp' for the full log"
    exit 1
else
    echo "Sync complete"
    rm $tmp
    exit 0
fi
