#!/usr/bin/env bash

status-bar() {
  ret=$?
  Grey='\[\e[1;32m\]'
  Green='\[\e[0;32m\]'
  LightGrey='\[\e[01;34m\]'
  White='\[\e[01;37m\]'
  Red='\[\e[01;31m\]'
  Reset='\[\e[00m\]'
  Checkmark='\342\234\223'
  FancyX='\342\234\227'

  PS1=""

  if [[ $EUID == 0 ]]; then
    PS1+="$Red\\h "
  else
    PS1+="$Grey\\u@\\h "
  fi

  PS1+="$LightGrey\\w "

  if [[ $(get-branch) ]]; then
    PS1+="$Green($(get-branch)) "
  fi

  PS1+="$LightGrey"

  if [[ $ret -eq 0 ]]; then
    PS1+="$Checkmark "
  else
    PS1+="$FancyX "
  fi

  PS1+="\$$Reset "
}
